### ISSUE TITLE
`covr` suggests you are not at 100% branch coverage

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/CrossR#34]
When running covr::report() it suggests you are not at 100% branch coverage:
![screen shot 2018-03-16 at 9 42 25 am](https://user-images.githubusercontent.com/6865016/37533207-6cfd391e-28fe-11e8-8821-0390bba17e2f.png)

**Comment by ttimbers** [comment]
Install the [`covr`](https://github.com/r-lib/covr) package and do this yourself - then when you get this table, click on the filenames in the File column for more information where you could be missing coverage.

**Comment by raffrica** [comment]
From most recent pull request by @ShunChi100 , 100% coverage
